- type: job
  id: Chemist
  name: job-name-chemist
  description: job-description-chemist
  playTimeTracker: JobChemist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 10800 #3 hrs
  startingGear: ChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Chemistry
  - Maintenance

- type: startingGear
  id: ChemistGear
  equipment:
    socks: ClothingUnderSocksOrangeKneeSocks
    jumpsuit: ClothingUniformJumpsuitChemistry
    back: ClothingBackpackChemistryFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLabChem
    id: ChemistryPDA
    ears: ClothingHeadsetMedical
    belt: ChemBag
    pocket1: HandLabeler
    # the purple glasses?
    eyes: ClothingEyesGlassesChemical
  innerclothingskirt: ClothingUniformJumpskirtChemistry
  femaleSocks: ClothingUnderSocksOrangeStockings
  satchel: ClothingBackpackSatchelChemistryFilled
  duffelbag: ClothingBackpackDuffelChemistryFilled
