## Static recipes

## Dynamic recipes

- type: latheRecipePack
  id: SecurityAmmoAdvanced
  recipes:
  - MagazinePistol
  - MagazinePistolRubber
  - MagazinePistolHighCapacity
  - MagazinePistolHighCapacityRubber
  - MagazineVectorPistolSmall
  - MagazineVectorPistolSmallRubber
  - MagazineVectorPistol
  - MagazineVectorPistolRubber
  - MagazinePistolSubMachineGun
  - MagazinePistolSubMachineGunRubber
  - MagazinePistolSubMachineGunTopMounted
  - MagazineVectorRifle
  - MagazineVectorRifleRubber
  - MagazineRifle
  - MagazineRifleRubber
  - MagazineRifleEmpty
  - MagazineRifleExt
  - MagazineRifleExtRubber
  - MagazineLightRifleRubber
  - MagazineShotgun
  - MagazineShotgunEmpty
  - MagazineShotgunSlug
  - SpeedLoaderMagnum
  - SpeedLoaderMagnumEmpty
  - MagazineShotgunSaiga
  - MagazineBoxMagnum
  - MagazineBoxPistolIncendiary
  - MagazineBoxPistolRubber
  - MagazineBoxRifleBig
  - MagazineBoxRifleIncendiary
  - MagazineBoxRifleRubber
  - BoxLethalshot
  - BoxShotgunIncendiary
  - BoxBeanbag
  - SpeedLoaderAntiMaterial
  - MagazineBoxAntiMaterielBig

- type: latheRecipePack
  id: SecurityWeaponsAdvanced
  recipes:
  - WeaponPistolMk58
  - WeaponPistolMk68
  - WeaponRevolverInspector
  - WeaponLaserGun
  - WeaponAdvancedLaser
  - WeaponSubMachineGunWt550
  - WeaponSubMachineGunVector
  - WeaponSubMachineGunDrozd
  - WeaponRifleLecter
  - WeaponLaserCarbine
  - WeaponLaserCannon
  - WeaponXrayCannon
  - WeaponShotgunKammerer
  - WeaponShotgunEnforcer
  - WeaponRevolverSuppressor
