- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:RoleTimeRequirement
<<<<<<< HEAD
      role: JobChiefEngineer
      time: 10800
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 10800
    - !type:RoleTimeRequirement
      role: JobChiefMedicalOfficer
      time: 10800
    - !type:OverallPlaytimeRequirement
      time: 216000
=======
      role: JobHeadOfPersonnel
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobChiefMedicalOfficer
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobChiefEngineer
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobResearchDirector
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobQuartermaster
      time: 21600 #6 hrs
>>>>>>> a2425cf7b1ef0a400695113a6ccc2bfb7985db07
  weight: 20
  startingGear: CaptainGear
  icon: "Captain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: CaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    back: ClothingBackpackCaptainFilled
    shoes: ClothingShoesColorBlack
    head: ClothingHeadHatCaptain
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    outerClothing: ClothingOuterArmorCaptainCarapace
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  innerclothingskirt: ClothingUniformJumpskirtCaptain
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled
