- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcomGear
  icon: "Nanotrasen"
  supervisors: job-supervisors-hos
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    back: ClothingBackpackSatchelCentcomFilled
    mask: ClothingMaskGasCentcom
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterVestKevlar
    id: CentcomPDA
    ears: ClothingHeadsetAltCommand
<<<<<<< HEAD
    pocket1: RubberStampCentcom
    pocket2: BoxFolderBlue
=======
    pocket1: PaperOffice
    pocket2: PenCentcom
>>>>>>> a2425cf7b1ef0a400695113a6ccc2bfb7985db07
