- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
<<<<<<< HEAD
      time: 36000
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000
    - !type:OverallPlaytimeRequirement
      time: 144000
=======
      time: 54000 # 15 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # 15 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 # 15 hrs
    - !type:DepartmentTimeRequirement
      department: Command
      time: 72000 # 20 hrs
>>>>>>> a2425cf7b1ef0a400695113a6ccc2bfb7985db07
  weight: 20
  startingGear: HoPGear
  icon: "HeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  # I mean they'll give themselves the rest of the access levels *anyways*.
  # As of 15/03/23 they can't do that so here's MOST of the rest of the access levels.
  # Head level access that isn't their own was deliberately left out, get AA from the captain instead.
  - Chemistry
  - Engineering
  - Quartermaster
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Cargo
  - Atmospherics
  - Cargo
  - Medical

- type: startingGear
  id: HoPGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpackHOPFilled
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatHopcap
    id: HoPPDA
    ears: ClothingHeadsetAltCommand
  innerclothingskirt: ClothingUniformJumpskirtHoP
  satchel: ClothingBackpackSatchelHOPFilled
  duffelbag: ClothingBackpackDuffelHOPFilled
