# HoS Timers
- type: loadoutEffectGroup
  id: HoSHonoraryTrenchTimer
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 180000 #50 hours

# Coats
- type: loadout
  id: HeadofSecurityHonoraryTrench
  equipment: HeadofSecurityHonoraryTrench
  effects:
  - !type:GroupLoadoutEffect
    proto: HoSHonoraryTrenchTimer

- type: startingGear
  id: HeadofSecurityHonoraryTrench
  equipment:
    id: ClothingOuterCoatHoSHonoraryTrench
