- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 18000
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 72000
  weight: 10
  startingGear: ChiefEngineerGear
  icon: "JobIconChiefEngineer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    socks: ClothingUnderSocksOrangeKneeSocks
    head: ClothingHeadHatHardhatWhite
    jumpsuit: ClothingUniformJumpsuitChiefEngineer
    back: ClothingBackpackChiefEngineerFilled
    shoes: ClothingShoesColorBrown
    id: CEPDA
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetCE
    belt: ClothingBeltUtilityEngineering
  innerclothingskirt: ClothingUniformJumpskirtChiefEngineer
  femaleSocks: ClothingUnderSocksOrangeStockings
  satchel: ClothingBackpackSatchelChiefEngineerFilled
  duffelbag: ClothingBackpackDuffelChiefEngineerFilled
