- type: job
  id: TechnicalAssistant
  name: job-name-technical-assistant
  description: job-description-technical-assistant
  playTimeTracker: JobTechnicalAssistant
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 3600 #1 hour (Anti-raid system?)
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 54000 #15 hrs
      inverted: true # stop playing intern if you're good at engineering!
  startingGear: TechnicalAssistantGear
  icon: "JobIconTechnicalAssistant"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External

- type: startingGear
  id: TechnicalAssistantGear
  equipment:
    socks: ClothingUnderSocksYellowKneeSocks
    head: ClothingHeadHatWelding
    jumpsuit: ClothingUniformJumpsuitColorYellow
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    id: TechnicalAssistantPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  innerclothingskirt: ClothingUniformJumpskirtColorYellow
  femaleSocks: ClothingUnderSocksYellowStockings
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
