- type: latheRecipe
  id: Handcuffs
  result: Handcuffs
  completetime: 2
  materials:
    Steel: 300

- type: latheRecipe
  id: Zipties
  result: Zipties
  completetime: 2
  materials:
    Plastic: 200

- type: latheRecipe
  id: Stunbaton
  result: Stunbaton
  completetime: 2
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  id: ForensicPad
  result: ForensicPad
  completetime: 4
  materials:
    Plastic: 100

- type: latheRecipe
  id: ClothingEyesGlassesSecurity
  result: ClothingEyesGlassesSecurity
  completetime: 2
  materials:
    Steel: 300
    Glass: 200

- type: latheRecipe
  id: RiotShield
  result: RiotShield
  completetime: 4
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  id: Flash
  result: Flash
  completetime: 2
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100

- type: latheRecipe
  id: ShellShotgunBeanbag
  result: ShellShotgunBeanbag
  completetime: 2
  materials:
    Plastic: 15
    Steel: 10

- type: latheRecipe
  id: CartridgePistolRubber
  result: CartridgePistolRubber
  completetime: 2
  materials:
    Plastic: 5
    Steel: 5

- type: latheRecipe
  id: CartridgeMagnumRubber
  result: CartridgeMagnumRubber
  completetime: 2
  materials:
    Plastic: 5
    Steel: 5

- type: latheRecipe
  id: CartridgeRifle
  result: CartridgeRifle
  completetime: 2
  materials:
    Steel: 15

- type: latheRecipe
  id: CartridgeLightRifleRubber
  result: CartridgeLightRifleRubber
  completetime: 2
  materials:
    Plastic: 10
    Steel: 5

- type: latheRecipe
  id: CartridgeRifleRubber
  result: CartridgeRifleRubber
  completetime: 2
  materials:
    Plastic: 10
    Steel: 5

- type: latheRecipe
  id: CartridgePistol
  result: CartridgePistol
  completetime: 2
  materials:
    Steel: 10

- type: latheRecipe
  id: ShellShotgun
  result: ShellShotgun
  completetime: 2
  materials:
    Steel: 20

- type: latheRecipe
  id: CartridgeMagnum
  result: CartridgeMagnum
  completetime: 2
  materials:
    Steel: 20

- type: latheRecipe
  id: CartridgeLightRifle
  result: CartridgeLightRifle
  completetime: 2
  materials:
    Steel: 30

- type: latheRecipe
  id: ShellShotgunFlare
  result: ShellShotgunFlare
  completetime: 2
  materials:
    Plastic: 20
    Steel: 5

- type: latheRecipe
  id: ShellTranquilizer
  result: ShellTranquilizer
  completetime: 4
  materials:
    Plastic: 15
    Steel: 10
    Glass: 5

- type: latheRecipe
  id: TargetHuman
  result: TargetHuman
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  id: TargetClown
  result: TargetClown
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  id: TargetSyndicate
  result: TargetSyndicate
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

# Magazines for SecurityTechFab and WeaponsTechFab
# Resource logic. [Number of rounds in magazine]*[Cartridge material] + 100 steel
# Complete time logic. [Number of rounds in magazine]*[Cartridge complete time] + 5
- type: latheRecipe
  id: MagazinePistolRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Pistol/pistol_mag.rsi
    state: rubber
  result: MagazinePistolRubber
  completetime: 10
  materials:
    Plastic: 50
    Steel: 150

- type: latheRecipe
  id: MagazineMagnumRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Magnum/magnum_mag.rsi
    state: rubber
  result: MagazineMagnumRubber
  completetime: 10
  materials:
    Plastic: 50
    Steel: 150

- type: latheRecipe
  id: MagazineCaselessRifleRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/CaselessRifle/caseless_rifle_mag.rsi
    state: rubber
  result: MagazineCaselessRifleRubber
  completetime: 20
  materials:
    Plastic: 300
    Steel: 250

- type: latheRecipe
  id: MagazineLightRifleRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/LightRifle/light_rifle_mag.rsi
    state: rubber
  result: MagazineLightRifleRubber
  completetime: 20
  materials:
    Plastic: 300
    Steel: 250

- type: latheRecipe
  id: MagazineRifleRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Rifle/rifle_mag.rsi
    state: rubber
  result: MagazineRifleRubber
  completetime: 20
  materials:
    Plastic: 250
    Steel: 225

- type: latheRecipe
  id: MagazinePistol
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Pistol/pistol_mag.rsi
    state: red
  result: MagazinePistol
  completetime: 10
  materials:
    Steel: 200

- type: latheRecipe
  id: MagazineMagnum
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Magnum/magnum_mag.rsi
    state: red
  result: MagazineMagnum
  completetime: 10
  materials:
    Steel: 300

- type: latheRecipe
  id: MagazineCaselessRifle
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/CaselessRifle/caseless_rifle_mag.rsi
    state: red
  result: MagazineCaselessRifle
  completetime: 20
  materials:
    Plastic: 300
    Steel: 250

- type: latheRecipe
  id: MagazineLightRifle
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/LightRifle/light_rifle_mag.rsi
    state: red
  result: MagazineLightRifle
  completetime: 20
  materials:
    Steel: 1000

- type: latheRecipe
  id: MagazineRifle
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Rifle/rifle_mag.rsi
    state: red
  result: MagazineRifle
  completetime: 20
  materials:
    Plastic: 250
    Steel: 225
# Magazines for SecurityTechFab
# Weapons kinetic
- type: latheRecipe
  id: WeaponRevolverInspector
  icon:
    sprite: Objects/Weapons/Guns/Revolvers/inspector.rsi
    state: icon
  result: WeaponRevolverInspector
  completetime: 15
  materials:
    Steel: 500

- type: latheRecipe
  id: WeaponSubMachineGunWt550
  icon:
    sprite: Objects/Weapons/Guns/SMGs/wt550.rsi
    state: base
  result: WeaponSubMachineGunWt550
  completetime: 30
  materials:
    Plastic: 200
    Steel: 1000

- type: latheRecipe
  id: WeaponRifleLecter
  icon:
    sprite: Objects/Weapons/Guns/Rifles/lecter.rsi
    state: base
  result: WeaponRifleLecter
  completetime: 30
  materials:
    Plastic: 200
    Steel: 1300

- type: latheRecipe
  id: WeaponShotgunDoubleBarreled
  icon:
    sprite: Objects/Weapons/Guns/Shotguns/db_shotgun.rsi
    state: icon
  result: WeaponShotgunDoubleBarreled
  completetime: 20
  materials:
    Wood: 500
    Steel: 500

- type: latheRecipe
  id: WeaponPistolMk58
  icon:
    sprite: Objects/Weapons/Guns/Pistols/mk58.rsi
    state: base
  result: WeaponPistolMk58
  completetime: 15
  materials:
    Steel: 500

- type: latheRecipe
  id: WeaponSubMachineGunVector
  icon:
    sprite: Objects/Weapons/Guns/SMGs/vector.rsi
    state: base
  result: WeaponSubMachineGunVector
  completetime: 30
  materials:
    Plastic: 200
    Steel: 800

# Weapons energy
- type: latheRecipe
  id: WeaponDisabler
  icon:
    sprite: Objects/Weapons/Guns/Battery/disabler.rsi
    state: base
  result: WeaponDisabler
  completetime: 15
  materials:
    Glass: 300
    Steel: 300

- type: latheRecipe
  id: WeaponDisablerPractice
  icon:
    sprite: Objects/Weapons/Guns/Battery/practice_disabler.rsi
    state: base
  result: WeaponDisablerPractice
  completetime: 15
  materials:
    Glass: 200
    Steel: 200

- type: latheRecipe
  id: WeaponLaserCarbine
  icon:
    sprite: Objects/Weapons/Guns/Battery/laser_gun.rsi
    state: base
  result: WeaponLaserCarbine
  completetime: 30
  materials:
    Glass: 500
    Plastic: 500
    Steel: 500

- type: latheRecipe
  id: WeaponAdvancedLaser
  icon:
    sprite: Objects/Weapons/Guns/Battery/advancedlasergun.rsi
    state: base
  result: WeaponAdvancedLaser
  completetime: 30
  materials:
    Gold: 1500
    Steel: 500
    Uranium: 500
    
- type: latheRecipe
  id: MagazineBoxPistol
  result: MagazineBoxPistol
  completetime: 5
  materials:
    Steel: 650

- type: latheRecipe
  id: MagazineBoxPistolRubber
  result: MagazineBoxPistolRubber
  completetime: 5
  materials:
    Steel: 350
    Plastic: 300

- type: latheRecipe
  id: MagazineBoxMagnum
  result: MagazineBoxMagnum
  completetime: 5
  materials:
    Steel: 1250

- type: latheRecipe
  id: MagazineBoxMagnumRubber
  result: MagazineBoxMagnumRubber
  completetime: 5
  materials:
    Steel: 350
    Plastic: 300

- type: latheRecipe
  id: MagazineBoxRifle
  result: MagazineBoxRifle
  completetime: 5
  materials: 
    Steel: 950

- type: latheRecipe
  id: MagazineBoxRifleRubber
  result: MagazineBoxRifleRubber
  completetime: 5
  materials:
    Steel: 350
    Plastic: 600

- type: latheRecipe
  id: MagazineBoxLightRifle
  result: MagazineBoxLightRifle
  completetime: 5
  materials:
    Steel: 1800

- type: latheRecipe
  id: MagazineBoxLightRifleRubber
  result: MagazineBoxLightRifleRubber
  completetime: 5
  materials:
    Steel: 350
    Plastic: 600
