- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Box
  - Cluster
  - Core
  - Fland
  - Marathon
  - MetaStation
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
  #- Train <- return after station anchoring PR is finished and merged
  - Driller
  - KiloStation
