- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  - Atlas
  - Bagel
  - Box
  - Cluster
  - Core
  - Fland
  - Gemini
  - Marathon
  - MetaStation
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
  - Driller
  - KiloStation
