- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Box
  - Cluster
  - Core
  - Fland
  - Marathon
  - MetaStation
  - Oasis
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
  #- Train
  - Driller
  - Lighthouse
  - Tehtra
  - Elstation
