#Cult outfit startingGear definitions.
- type: startingGear
  id: CultLeaderGear
  equipment:
    socks: ClothingUnderSocksBlackSocks
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpackFilled
    head: ClothingHeadHelmetCult
    neck: BedsheetCult
    outerClothing: ClothingOuterArmorCult
    shoes: ClothingShoesCult
    id: PassengerPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtColorBlack
  femaleSocks: ClothingUnderSocksBlackKneeSocks
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: CultistGear
  equipment:
    socks: ClothingUnderSocksBlackSocks
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpackFilled
    head: ClothingHeadHatHoodCulthood
    outerClothing: ClothingOuterRobesCult
    shoes: ClothingShoesColorRed
    id: PassengerPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtColorBlack
  femaleSocks: ClothingUnderSocksBlackKneeSocks
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
