#Misc outfit startingGear definitions.

#IHS Void Suit Outfit
- type: startingGear
  id: IHSGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpackFilled
    head: ClothingHeadHelmetIHSVoidHelm
    gloves: ClothingHandsGlovesIhscombat
    outerClothing: IHSVoidsuit
    shoes: ClothingShoesBootsJack
    id: PassengerPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtColorBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

#Skeleton Biker
- type: startingGear
  id: SkeletonBiker
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpackFilled
    head: HatBandSkull
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: ClothingOuterCoatGentle
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesBootsJack
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    pocket1: VehicleSkeletonMotorcycle
    pocket2: VehicleKeySkeletonMotorcycle
  innerclothingskirt: ClothingUniformJumpskirtColorBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

#Space Ninja Outfit
- type: startingGear
  id: SpaceNinjaGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpackFilled
    head: ClothingHeadHelmetSpaceNinja
    gloves: ClothingHandsGlovesSpaceNinja
    outerClothing: ClothingOuterSuitSpaceninja
    shoes: ClothingShoesSpaceNinja
    id: PassengerPDA
  innerclothingskirt: ClothingUniformJumpskirtColorBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

#Deathsquad Outfit
- type: startingGear
  id: DeadsquadGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquadOfficer
    back: ClothingBackpackDeathSquadOfficerFilled
    mask: ClothingMaskGasSwat
    eyes: ClothingEyesHudMedical
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitDeathsquad
    suitstorage: JetpackVoidFilled
    shoes: ClothingShoesBootsMagAdv
    id: ERTLeaderPDA
    pocket1: EnergySword
    belt: ClothingBeltChiefEngineerFilled


# Syndicate Operative Outfit - Poverty
- type: startingGear
  id: SyndicateOperativeGearExtremelyBasic
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    shoes: ClothingShoesBootsCombatFilled
  innerclothingskirt: ClothingUniformJumpsuitOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative


#Syndicate Operative Outfit - Basic
- type: startingGear
  id: SyndicateOperativeGearBasic
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsCombatFilled
    pocket1: BaseUplinkRadio30TC
    id: AgentIDCard
  innerclothingskirt: ClothingUniformJumpsuitOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative

#Syndicate Operative Outfit - Full Kit
- type: startingGear
  id: SyndicateOperativeGearFull
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    mask: ClothingMaskGasSyndicate
  # eyes: Night Vision Goggles whenever they're made
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndie
    shoes: ClothingShoesBootsCombatFilled
    id: AgentIDCard
    pocket1: ExtendedEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio30TC
    belt: ClothingBeltMilitaryWebbing
  innerclothingskirt: ClothingUniformJumpskirtOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative

- type: startingGear
  id: SyndicateCommanderGearFull
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    mask: ClothingMaskGasSyndicate
  # eyes: Night Vision Goggles whenever they're made
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndieCommander
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket1: ExtendedEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio30TC
    belt: ClothingBeltMilitaryWebbing
  innerclothingskirt: ClothingUniformJumpskirtOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative

- type: startingGear
  id: SyndicateOperativeMedicFull
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperativeMedic
    mask: ClothingMaskBreathMedical
    eyes: ClothingEyesHudMedical
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndieElite
    shoes: ClothingShoesBootsMagSyndie
    id: SyndiPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio30TC
    belt: ClothingBeltMilitaryWebbingMedFilled
  innerclothingskirt: ClothingUniformJumpskirtOperative
  satchel: ClothingBackpackDuffelSyndicateOperativeMedic
  duffelbag: ClothingBackpackDuffelSyndicateOperativeMedic

#CBURN Unit Gear - Full Kit
- type: startingGear
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCBURNAgent
    back: ClothingBackpackCBURNAgentFilled
    mask: ClothingMaskGasSwat
    eyes: ClothingEyesHudMedical
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesBootsCombatFilled
    id: CBURNPDA
    pocket1: WeaponLaserGun
    suitstorage: YellowOxygenTankFilled
    belt: ClothingBeltSecurityWebbing

- type: startingGear
  id: BoxingKangarooGear
  equipment:
    gloves: ClothingHandsGlovesBoxingBlue
