#Wizard outfit startingGear definitions.
- type: startingGear
  id: WizardBlueGear
  equipment:
    socks: ClothingUnderSocksBlueKneeSocks
    jumpsuit: ClothingUniformJumpsuitColorDarkBlue
    back: ClothingBackpackFilled
    head: ClothingHeadHatWizard
    outerClothing: ClothingOuterWizard
    shoes: ClothingShoesWizard
    id: PassengerPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtColorDarkBlue
  femaleSocks: ClothingUnderSocksBlueStockings
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: WizardRedGear
  equipment:
    socks: ClothingUnderSocksRedKneeSocks
    jumpsuit: ClothingUniformJumpsuitColorRed
    back: ClothingBackpackFilled
    head: ClothingHeadHatRedwizard
    outerClothing: ClothingOuterWizardRed
    shoes: ClothingShoesWizard
    id: PassengerPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtColorRed
  femaleSocks: ClothingUnderSocksRedStockings
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: WizardVioletGear
  equipment:
    socks: ClothingUnderSocksPurpleKneeSocks
    jumpsuit: ClothingUniformJumpsuitColorPurple
    back: ClothingBackpackFilled
    head: ClothingHeadHatVioletwizard
    outerClothing: ClothingOuterWizardViolet
    shoes: ClothingShoesWizard
    id: PassengerPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtColorPurple
  femaleSocks: ClothingUnderSocksPurpleStockings
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: WizardHardsuitGear
  equipment:
    socks: ClothingUnderSocksPurpleKneeSocks
    jumpsuit: ClothingUniformJumpsuitColorPurple
    back: ClothingBackpackFilled
    outerClothing: ClothingOuterHardsuitWizard
    shoes: ClothingShoesWizard
    id: PassengerPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtColorPurple
  femaleSocks: ClothingUnderSocksPurpleStockings
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
