- type: job
  id: Miner
  name: job-name-miner
  description: job-description-miner
  playTimeTracker: JobMiner
  requirements:
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 18000 #5 hrs
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 36000 #10 hours
  icon: "JobIconShaftMiner"
  startingGear: MinerGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External
  - Miner

- type: startingGear
  id: MinerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMiner
    back: ClothingBackpackSalvage
    shoes: ClothingShoesBootsSalvage
    id: MinerPDA
    ears: ClothingHeadsetMining
  satchel: ClothingBackpackSatchelSalvageFilled
  duffelbag: ClothingBackpackDuffelSalvageFilled
