- type: job
  id: Miner
  name: job-name-miner
  description: job-description-miner
  playTimeTracker: JobMiner
  requirements:
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 18000 #5 hrs
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 36000 #10 hours
  icon: "JobIconShaftMiner"
  startingGear: MinerGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: MinerGear
  equipment:
<<<<<<< HEAD
    socks: ClothingUnderSocksWhiteKneeSocks
=======
>>>>>>> 64563ca5c19004bd3d9c92680e519a731ac1b0b8
    jumpsuit: ClothingUniformJumpsuitMiner
    back: ClothingBackpackSalvageFilled
    shoes: ClothingShoesBootsSalvage
    id: MinerPDA
    ears: ClothingHeadsetMining
  satchel: ClothingBackpackSatchelSalvageFilled
  duffelbag: ClothingBackpackDuffelSalvageFilled
<<<<<<< HEAD
  femaleSocks: ClothingUnderSocksWhiteStockings
=======
>>>>>>> 64563ca5c19004bd3d9c92680e519a731ac1b0b8
