- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
<<<<<<< HEAD
      time: 18000
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 72000
=======
      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 108000 # 30 hrs
>>>>>>> a2425cf7b1ef0a400695113a6ccc2bfb7985db07
  weight: 10
  startingGear: QuartermasterGear
  icon: "QuarterMaster"
  supervisors: job-supervisors-hop
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command

- type: startingGear
  id: QuartermasterGear
  equipment:
    head: ClothingHeadHatQMsoft
    jumpsuit: ClothingUniformJumpsuitQM
    back: ClothingBackpackQuartermasterFilled
    shoes: ClothingShoesColorBrown
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    pocket1: AppraisalTool
  innerclothingskirt: ClothingUniformJumpskirtQM
  satchel: ClothingBackpackSatchelQuartermasterFilled
  duffelbag: ClothingBackpackDuffelQuartermasterFilled
