- type: job
  id: Janitor
  name: job-name-janitor
  description: job-description-janitor
  playTimeTracker: JobJanitor
  startingGear: JanitorGear
  icon: "JobIconJanitor"
  supervisors: job-supervisors-hop
  access:
  - Janitor
  - Maintenance
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: WeaponRevolverInspector

- type: startingGear
  id: JanitorGear
  equipment:
    socks: ClothingUnderSocksPurpleSocks
    jumpsuit: ClothingUniformJumpsuitJanitor
    back: ClothingBackpackFilled
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHatPurplesoft
    id: JanitorPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
  innerClothingSkirt: ClothingUniformJumpskirtJanitor
  femaleSocks: ClothingUnderSocksPurpleKneeSocks
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: JanitorMaidGear
  equipment:
    socks: ClothingUnderSocksWhiteStockings
    jumpsuit: ClothingUniformJumpskirtJanimaid
    back: ClothingBackpackFilled
    id: JanitorPDA
    head: ClothingHeadHatCatEars
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
  innerClothingSkirt: ClothingUniformJumpskirtJanimaid
  femaleSocks: ClothingUnderSocksWhiteStockings
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
