- type: startingGear
  id: PirateGear
  equipment:
    socks: ClothingUnderSocksBlackSocks
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadBandBlack
    shoes: ClothingShoesBootsLaceup
    id: PassengerPDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
  innerclothingskirt: ClothingUniformJumpsuitPirate
  femaleSocks: ClothingUnderSocksBlackKneeSocks
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled

- type: startingGear
  id: PirateCaptainGear
  equipment:
    socks: ClothingUnderSocksBlackKneeSocks
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadHatPirate
    shoes: ClothingShoesBootsLaceup
    id: PassengerPDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
    pocket2: EnergyCutlass
    outerClothing: ClothingOuterCoatPirate
  innerclothingskirt: ClothingUniformJumpskirtColorLightBrown
  femaleSocks: ClothingUnderSocksBlackStockings
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled

- type: startingGear
  id: PirateFirstmateGear
  equipment:
    socks: ClothingUnderSocksWhiteKneeSocks
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadHatPirateTricord
    shoes: ClothingShoesBootsLaceup
    id: PassengerPDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
    outerClothing: ClothingOuterCoatGentle
  innerclothingskirt: ClothingUniformJumpsuitPirate
  femaleSocks: ClothingUnderSocksWhiteKneeSocks
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled
